
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  resources:
    static-locations: "classpath:/static/"
server:
  port: 8181
  servlet:
    context-path: "/api"